/*
 * Copyright (C) 2017 jason
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package deprecated;

import com.pi4j.io.i2c.I2CFactory;
import iGEM2017.RgbSensor;
import iGEM2017.LuxSensor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author jason
 */
public class MainWindow_01 extends javax.swing.JFrame {

    // How many milliseconds between sensor updates?
    private final int SENSOR_UPDATE_DELAY = 300;

    private RgbSensor colorSensor;
    private LuxSensor luxSensor;
    // TODO: Add temp/humidity sensor
    private Timer timer;

    /**
     * Creates new form MainWindow
     */
    public MainWindow_01() {
        initComponents();
        //initializeSensors();
        //createUpdateTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        staticLabelTemp = new javax.swing.JLabel();
        labelTemp = new javax.swing.JLabel();
        panelTemp = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        staticLabelColor = new javax.swing.JLabel();
        panelColorRaw = new javax.swing.JPanel();
        staticLabelColorRaw = new javax.swing.JLabel();
        staticLabelColorNorm = new javax.swing.JLabel();
        labelColorRaw = new javax.swing.JLabel();
        labelColorNorm = new javax.swing.JLabel();
        panelColorRaw1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        staticLabelTurb = new javax.swing.JLabel();
        labelTurb = new javax.swing.JLabel();
        panelTurb = new javax.swing.JPanel();
        staticLabelTemp1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        staticLabelTemp2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        staticLabelTemp3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        staticLabelTemp4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        staticLabelColorRaw1 = new javax.swing.JLabel();
        staticLabelColorRaw2 = new javax.swing.JLabel();
        staticLabelColorRaw3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 128, 128));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setSize(new java.awt.Dimension(800, 480));

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));

        jPanel2.setBackground(new java.awt.Color(20, 20, 40));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 188, 247)));
        jPanel2.setForeground(new java.awt.Color(111, 188, 247));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 100));

        staticLabelTemp.setFont(new java.awt.Font("Abel", 1, 24)); // NOI18N
        staticLabelTemp.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelTemp.setText("Temperature");

        labelTemp.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        labelTemp.setForeground(new java.awt.Color(210, 250, 255));
        labelTemp.setText("000000°C");

        panelTemp.setBackground(new java.awt.Color(90, 90, 90));
        panelTemp.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout panelTempLayout = new javax.swing.GroupLayout(panelTemp);
        panelTemp.setLayout(panelTempLayout);
        panelTempLayout.setHorizontalGroup(
            panelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        panelTempLayout.setVerticalGroup(
            panelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staticLabelTemp)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTemp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(staticLabelTemp)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(20, 20, 40));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 188, 247)));
        jPanel3.setForeground(new java.awt.Color(111, 188, 247));
        jPanel3.setToolTipText("");
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 100));

        staticLabelColor.setFont(new java.awt.Font("Abel", 1, 24)); // NOI18N
        staticLabelColor.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelColor.setText("Color");

        panelColorRaw.setBackground(new java.awt.Color(90, 90, 90));
        panelColorRaw.setMaximumSize(new java.awt.Dimension(40, 40));
        panelColorRaw.setMinimumSize(new java.awt.Dimension(40, 40));
        panelColorRaw.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelColorRawLayout = new javax.swing.GroupLayout(panelColorRaw);
        panelColorRaw.setLayout(panelColorRawLayout);
        panelColorRawLayout.setHorizontalGroup(
            panelColorRawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
        panelColorRawLayout.setVerticalGroup(
            panelColorRawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        staticLabelColorRaw.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        staticLabelColorRaw.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelColorRaw.setText("Raw Reading");

        staticLabelColorNorm.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        staticLabelColorNorm.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelColorNorm.setText("Normalized");

        labelColorRaw.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        labelColorRaw.setForeground(new java.awt.Color(210, 250, 255));
        labelColorRaw.setText("000000");

        labelColorNorm.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        labelColorNorm.setForeground(new java.awt.Color(210, 250, 255));
        labelColorNorm.setText("000000");

        panelColorRaw1.setBackground(new java.awt.Color(90, 90, 90));
        panelColorRaw1.setMaximumSize(new java.awt.Dimension(40, 40));
        panelColorRaw1.setMinimumSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelColorRaw1Layout = new javax.swing.GroupLayout(panelColorRaw1);
        panelColorRaw1.setLayout(panelColorRaw1Layout);
        panelColorRaw1Layout.setHorizontalGroup(
            panelColorRaw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
        panelColorRaw1Layout.setVerticalGroup(
            panelColorRaw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staticLabelColor)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelColorRaw, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelColorRaw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staticLabelColorRaw)
                            .addComponent(labelColorRaw)
                            .addComponent(staticLabelColorNorm)
                            .addComponent(labelColorNorm))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(staticLabelColor)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(staticLabelColorRaw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelColorRaw))
                    .addComponent(panelColorRaw, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(staticLabelColorNorm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelColorNorm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelColorRaw1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        jPanel4.setBackground(new java.awt.Color(20, 20, 40));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 188, 247)));
        jPanel4.setForeground(new java.awt.Color(111, 188, 247));
        jPanel4.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(300, 100));

        staticLabelTurb.setFont(new java.awt.Font("Abel", 1, 24)); // NOI18N
        staticLabelTurb.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelTurb.setText("Turbidity");

        labelTurb.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        labelTurb.setForeground(new java.awt.Color(210, 250, 255));
        labelTurb.setText("000000");

        panelTurb.setBackground(new java.awt.Color(90, 90, 90));
        panelTurb.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout panelTurbLayout = new javax.swing.GroupLayout(panelTurb);
        panelTurb.setLayout(panelTurbLayout);
        panelTurbLayout.setHorizontalGroup(
            panelTurbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        panelTurbLayout.setVerticalGroup(
            panelTurbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staticLabelTurb)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(panelTurb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTurb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(staticLabelTurb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTurb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTurb, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staticLabelTemp1.setFont(new java.awt.Font("Abel", 1, 30)); // NOI18N
        staticLabelTemp1.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelTemp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staticLabelTemp1.setText("Pump Control");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        staticLabelTemp2.setFont(new java.awt.Font("Abel", 1, 30)); // NOI18N
        staticLabelTemp2.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelTemp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staticLabelTemp2.setText("Sensor Readings");

        jPanel5.setBackground(new java.awt.Color(20, 20, 40));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 188, 247)));
        jPanel5.setForeground(new java.awt.Color(111, 188, 247));
        jPanel5.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(300, 100));

        staticLabelTemp3.setFont(new java.awt.Font("Abel", 1, 24)); // NOI18N
        staticLabelTemp3.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelTemp3.setText("Calibrate");

        jButton1.setText("Green");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Purple");

        jButton3.setText("Media");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staticLabelTemp3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(staticLabelTemp3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(20, 20, 40));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 188, 247)));
        jPanel6.setForeground(new java.awt.Color(111, 188, 247));
        jPanel6.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(300, 100));

        staticLabelTemp4.setFont(new java.awt.Font("Abel", 1, 24)); // NOI18N
        staticLabelTemp4.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelTemp4.setText("Manual Activation");

        jButton4.setText("Fill Pump");

        jButton5.setText("Dispense");

        jButton7.setText("Dispense");

        jButton8.setText("Fill Pump");

        jButton9.setText("Fill Pump");

        jButton10.setText("Dispense");

        staticLabelColorRaw1.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        staticLabelColorRaw1.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelColorRaw1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staticLabelColorRaw1.setText("Green");

        staticLabelColorRaw2.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        staticLabelColorRaw2.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelColorRaw2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staticLabelColorRaw2.setText("Purple");

        staticLabelColorRaw3.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        staticLabelColorRaw3.setForeground(new java.awt.Color(210, 250, 255));
        staticLabelColorRaw3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staticLabelColorRaw3.setText("Media");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(staticLabelColorRaw1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(staticLabelColorRaw2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(staticLabelColorRaw3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton8)
                                            .addComponent(jButton4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jButton7)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(staticLabelTemp4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(staticLabelTemp4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staticLabelColorRaw1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(staticLabelColorRaw2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(staticLabelColorRaw3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(staticLabelTemp2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(staticLabelTemp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(staticLabelTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(staticLabelTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow_01().setVisible(true);
            }
        });

    }

    public void initializeSensors() {
        try {
            this.colorSensor = new RgbSensor();
            this.luxSensor = new LuxSensor((byte) 0x39);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow_01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (I2CFactory.UnsupportedBusNumberException ex) {
            Logger.getLogger(MainWindow_01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainWindow_01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void createUpdateTimer() {
        this.timer = new Timer(SENSOR_UPDATE_DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                updateColorSensor();
                updateLuxSensor();
                updateTempSensor();
            }
        });
    }
    
    public void updateColorSensor() {
        // TODO
    }
    
    public void updateLuxSensor() {
        // TODO
    }
    
    public void updateTempSensor() {
        // TODO
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelColorNorm;
    private javax.swing.JLabel labelColorRaw;
    private javax.swing.JLabel labelTemp;
    private javax.swing.JLabel labelTurb;
    private javax.swing.JPanel panelColorRaw;
    private javax.swing.JPanel panelColorRaw1;
    private javax.swing.JPanel panelTemp;
    private javax.swing.JPanel panelTurb;
    private javax.swing.JLabel staticLabelColor;
    private javax.swing.JLabel staticLabelColorNorm;
    private javax.swing.JLabel staticLabelColorRaw;
    private javax.swing.JLabel staticLabelColorRaw1;
    private javax.swing.JLabel staticLabelColorRaw2;
    private javax.swing.JLabel staticLabelColorRaw3;
    private javax.swing.JLabel staticLabelTemp;
    private javax.swing.JLabel staticLabelTemp1;
    private javax.swing.JLabel staticLabelTemp2;
    private javax.swing.JLabel staticLabelTemp3;
    private javax.swing.JLabel staticLabelTemp4;
    private javax.swing.JLabel staticLabelTurb;
    // End of variables declaration//GEN-END:variables
}
