/*
 * Copyright (C) 2017 Washington iGEM Team 2017 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package launcher;

import com.pi4j.io.i2c.I2CFactory;
import iGEM2017.MainWindow;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pumpDiagnostics.PumpDiagGui;
import sensorGui.SensorGui;

/**
 *
 * @author Washington iGEM Team 2017
 */
public class LauncherWindow extends javax.swing.JFrame {

    /**
     * Creates new form LauncherWindo
     */
    public LauncherWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Chromastat Main Window");
        jButton1.setMaximumSize(new java.awt.Dimension(200, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchCstat(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Sensor Gui");
        jButton2.setMaximumSize(new java.awt.Dimension(200, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(200, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(200, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchSensorGui(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Pump Diagnostics");
        jButton3.setMaximumSize(new java.awt.Dimension(200, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(200, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(200, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchPumpDiagnostics(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launchCstat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchCstat

        try {
            MainWindow mainWindow = new MainWindow();
            mainWindow.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (I2CFactory.UnsupportedBusNumberException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_launchCstat

    private void launchSensorGui(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchSensorGui
        SensorGui sensorGui;
        try {
            sensorGui = new SensorGui();
            sensorGui.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (I2CFactory.UnsupportedBusNumberException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_launchSensorGui

    private void launchPumpDiagnostics(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchPumpDiagnostics
        try {
            PumpDiagGui pumpDiagGui;
            pumpDiagGui = new PumpDiagGui();
            pumpDiagGui.setVisible(true);
            this.setVisible(false);
        } catch (I2CFactory.UnsupportedBusNumberException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LauncherWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_launchPumpDiagnostics

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables

}
